defmodule OdinMarket.Repo.Migrations.AddShippingAndCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:listings) do
      add :shipping_cents, :bigint, null: false, default: 0
    end

    alter table(:orders) do
      add :shipping_cents, :bigint, null: false, default: 0
    end

    create table(:payment_cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stripe_payment_method_id, :text, null: false
      add :brand, :text, null: false
      add :last4, :text, null: false
      add :exp_month, :bigint
      add :exp_year, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "payment_cards_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:payment_cards, [:stripe_payment_method_id],
             name: "payment_cards_unique_method_index"
           )
  end

  def down do
    drop constraint(:payment_cards, "payment_cards_user_id_fkey")

    drop_if_exists unique_index(:payment_cards, [:stripe_payment_method_id],
                     name: "payment_cards_unique_method_index"
                   )

    drop table(:payment_cards)

    alter table(:orders) do
      remove :shipping_cents
    end

    alter table(:listings) do
      remove :shipping_cents
    end
  end
end
