defmodule OdinMarket.Repo.Migrations.Marketplace do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :buyer_id,
          references(:users,
            column: :id,
            name: "conversations_buyer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :vendor_id, :uuid, null: false
      add :listing_id, :uuid, null: false
    end

    create unique_index(:conversations, [:buyer_id, :vendor_id, :listing_id],
             name: "conversations_unique_thread_index"
           )

    create table(:listing_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :url, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :listing_id, :uuid, null: false
    end

    create table(:listings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:conversations) do
      modify :listing_id,
             references(:listings,
               column: :id,
               name: "conversations_listing_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:listing_images) do
      modify :listing_id,
             references(:listings,
               column: :id,
               name: "listing_images_listing_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:listings) do
      add :title, :text, null: false
      add :slug, :text, null: false
      add :description, :text
      add :kind, :text, null: false
      add :price_cents, :bigint, null: false
      add :currency, :text, null: false, default: "usd"
      add :qty_available, :bigint
      add :lead_days, :bigint
      add :specs, :map, null: false, default: %{}
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vendor_id, :uuid, null: false
    end

    create unique_index(:listings, [:slug], name: "listings_unique_slug_index")

    alter table(:listings) do
      add :category_id,
          references(:categories,
            column: :id,
            name: "listings_category_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false
      add :read_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "messages_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :sender_id,
          references(:users,
            column: :id,
            name: "messages_sender_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:orders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :qty, :bigint, null: false
      add :unit_price_cents, :bigint, null: false
      add :currency, :text, null: false, default: "usd"
      add :status, :text, null: false, default: "pending_payment"
      add :notes, :text
      add :note, :text
      add :stripe_checkout_session_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :buyer_id,
          references(:users,
            column: :id,
            name: "orders_buyer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :vendor_id, :uuid, null: false

      add :listing_id,
          references(:listings,
            column: :id,
            name: "orders_listing_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:users) do
      add :display_name, :text, null: false, default: "Member"
      add :role, :text, null: false, default: "customer"
      add :avatar_url, :text
      add :stripe_customer_id, :text
    end

    create table(:vendor_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:conversations) do
      modify :vendor_id,
             references(:vendor_profiles,
               column: :id,
               name: "conversations_vendor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:listings) do
      modify :vendor_id,
             references(:vendor_profiles,
               column: :id,
               name: "listings_vendor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:orders) do
      modify :vendor_id,
             references(:vendor_profiles,
               column: :id,
               name: "orders_vendor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:vendor_profiles) do
      add :shop_name, :text, null: false
      add :slug, :text, null: false
      add :bio, :text
      add :location, :text
      add :website, :text
      add :status, :text, null: false, default: "active"
      add :stripe_account_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "vendor_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:vendor_profiles, [:slug], name: "vendor_profiles_unique_slug_index")

    create unique_index(:vendor_profiles, [:user_id], name: "vendor_profiles_unique_user_index")
  end

  def down do
    drop constraint(:vendor_profiles, "vendor_profiles_user_id_fkey")

    drop_if_exists unique_index(:vendor_profiles, [:user_id],
                     name: "vendor_profiles_unique_user_index"
                   )

    drop_if_exists unique_index(:vendor_profiles, [:slug],
                     name: "vendor_profiles_unique_slug_index"
                   )

    alter table(:vendor_profiles) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :stripe_account_id
      remove :status
      remove :website
      remove :location
      remove :bio
      remove :slug
      remove :shop_name
    end

    drop constraint(:orders, "orders_listing_id_fkey")

    drop constraint(:orders, "orders_vendor_id_fkey")

    drop constraint(:orders, "orders_buyer_id_fkey")

    alter table(:orders) do
      modify :vendor_id, :uuid
    end

    drop constraint(:listings, "listings_category_id_fkey")

    drop constraint(:listings, "listings_vendor_id_fkey")

    alter table(:listings) do
      modify :vendor_id, :uuid
    end

    drop constraint(:conversations, "conversations_listing_id_fkey")

    drop constraint(:conversations, "conversations_vendor_id_fkey")

    drop constraint(:conversations, "conversations_buyer_id_fkey")

    alter table(:conversations) do
      modify :vendor_id, :uuid
    end

    drop table(:vendor_profiles)

    alter table(:users) do
      remove :stripe_customer_id
      remove :avatar_url
      remove :role
      remove :display_name
    end

    drop table(:orders)

    drop constraint(:messages, "messages_sender_id_fkey")

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop table(:messages)

    alter table(:listings) do
      remove :category_id
    end

    drop_if_exists unique_index(:listings, [:slug], name: "listings_unique_slug_index")

    alter table(:listings) do
      remove :vendor_id
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :specs
      remove :lead_days
      remove :qty_available
      remove :currency
      remove :price_cents
      remove :kind
      remove :description
      remove :slug
      remove :title
    end

    drop constraint(:listing_images, "listing_images_listing_id_fkey")

    alter table(:listing_images) do
      modify :listing_id, :uuid
    end

    alter table(:conversations) do
      modify :listing_id, :uuid
    end

    drop table(:listings)

    drop table(:listing_images)

    drop_if_exists unique_index(:conversations, [:buyer_id, :vendor_id, :listing_id],
                     name: "conversations_unique_thread_index"
                   )

    drop table(:conversations)

    drop_if_exists unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    drop table(:categories)
  end
end
