defmodule OdinMarket.Repo.Migrations.AddStaffDesk do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:moderation_audits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :target_type, :text, null: false
      add :target_id, :uuid, null: false
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "moderation_audits_actor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :target_type, :text, null: false
      add :target_id, :uuid, null: false
      add :reason, :text, null: false
      add :note, :text
      add :excerpt, :text
      add :reporter_name, :text, null: false
      add :subject_name, :text
      add :status, :text, null: false, default: "open"
      add :resolution_note, :text
      add :handled_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :reporter_id,
          references(:users,
            column: :id,
            name: "reports_reporter_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :subject_id,
          references(:users,
            column: :id,
            name: "reports_subject_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :handler_id,
          references(:users,
            column: :id,
            name: "reports_handler_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:users) do
      add :policy_accepted_at, :utc_datetime_usec
      add :policy_version, :text
    end

    alter table(:vendor_profiles) do
      add :held, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:vendor_profiles) do
      remove :held
    end

    alter table(:users) do
      remove :policy_version
      remove :policy_accepted_at
    end

    drop constraint(:reports, "reports_handler_id_fkey")

    drop constraint(:reports, "reports_subject_id_fkey")

    drop constraint(:reports, "reports_reporter_id_fkey")

    drop table(:reports)

    drop constraint(:moderation_audits, "moderation_audits_actor_id_fkey")

    drop table(:moderation_audits)
  end
end
