defmodule OdinMarket.Repo.Migrations.AddCategoryTreeAndAccountDeletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:categories) do
      add :parent_id,
          references(:categories,
            column: :id,
            name: "categories_parent_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:users) do
      add :deleted_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:users) do
      remove :deleted_at
    end

    drop constraint(:categories, "categories_parent_id_fkey")

    alter table(:categories) do
      remove :parent_id
    end
  end
end
