defmodule OdinMarket.Repo.Migrations.AddCartAndShipping do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cart_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :qty, :bigint, null: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :buyer_id,
          references(:users,
            column: :id,
            name: "cart_items_buyer_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :listing_id,
          references(:listings,
            column: :id,
            name: "cart_items_listing_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:cart_items, [:buyer_id, :listing_id],
             name: "cart_items_unique_line_index"
           )

    alter table(:orders) do
      add :ship_name, :text
      add :ship_line1, :text
      add :ship_line2, :text
      add :ship_city, :text
      add :ship_region, :text
      add :ship_postal_code, :text
      add :ship_country, :text
    end

    alter table(:users) do
      add :ship_name, :text
      add :ship_line1, :text
      add :ship_line2, :text
      add :ship_city, :text
      add :ship_region, :text
      add :ship_postal_code, :text
      add :ship_country, :text
    end
  end

  def down do
    alter table(:users) do
      remove :ship_country
      remove :ship_postal_code
      remove :ship_region
      remove :ship_city
      remove :ship_line2
      remove :ship_line1
      remove :ship_name
    end

    alter table(:orders) do
      remove :ship_country
      remove :ship_postal_code
      remove :ship_region
      remove :ship_city
      remove :ship_line2
      remove :ship_line1
      remove :ship_name
    end

    drop constraint(:cart_items, "cart_items_listing_id_fkey")

    drop constraint(:cart_items, "cart_items_buyer_id_fkey")

    drop_if_exists unique_index(:cart_items, [:buyer_id, :listing_id],
                     name: "cart_items_unique_line_index"
                   )

    drop table(:cart_items)
  end
end
